; Lines starting ; (semicolons) are commented out.
; That is, they do not affect the code and are here for demonstration purposes only.
; ----------------------------------

[Rainmeter]
; This section contains general settings that can be used to change how Rainmeter behaves.
Update=1000
Background=#@#Background.png
; #@# is equal to Rainmeter\Skins\illustro\@Resources
BackgroundMode=3
BackgroundMargins=0,35,5,10

[Metadata]
; Contains basic information of the skin.
Author=pein (Kucharskov mod)
Description=Based on illustro (2020)
License=Creative Commons BY-NC-SA 3.0
Version=1.0.1

[Variables]
; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
fontName=Roboto
textSize=8
colorBar=7,101,238,205
colorText=255,255,255,205
UrlAPI=https://example.com/api

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------
[measureGetData]
Measure=Plugin
Plugin=WebParser
UpdateRate=60
Url=#UrlAPI#
RegExp="(.*)"
StringIndex=1

[measureStatus]
Measure=Plugin
Plugin=WebParser
URL=[measureGetData]
RegExp=(?sU).*"sensorState":"(.*)"
StringIndex=1
StringIndex2=1
Substitute="":"..."

[measureLastSG]
Measure=Plugin
Plugin=WebParser
URL=[measureGetData]
RegExp=(?sU).*"sg":(.*)[,}]
StringIndex=1
StringIndex2=1
RegExpSubstitute=1
Substitute="":"N/A","^0$":"Brak"

[measureTime]
Measure=Plugin
Plugin=WebParser
URL=[measureGetData]
RegExp=(?sU).*"timestamp":"(.*)"
StringIndex=1
StringIndex2=1

[measureTimeParsed]
Measure=Time
TimeStamp=[measureTime]
TimeStampFormat=%Y-%m-%dT%H:%M:%S
Format=%d-%m-%Y %H:%M
Substitute="01-01-1601 00:00":"N/A"
DynamicVariables=1

[measurePumpBattery]
Measure=Plugin
Plugin=WebParser
URL=[measureGetData]
RegExp=(?sU).*"pumpBatteryLevelPercent":(.*),
StringIndex=1
StringIndex2=1
MinValue=0
MaxValue=100
Substitute="":"N/A","-1":"Brak "

[measureSensorBattery]
Measure=Plugin
Plugin=WebParser
URL=[measureGetData]
RegExp=(?sU).*"gstBatteryLevel":(.*),
StringIndex=1
StringIndex2=1
MinValue=0
MaxValue=100
Substitute="":"N/A","-1":"Brak "

[measureZero]
Measure=Calc
Formula=0

; ----------------------------------
; STYLES are used to "centralize" options
; ----------------------------------

[styleTitle]
StringAlign=CENTER
StringCase=UPPER
StringStyle=NORMAL
StringEffect=SHADOW
FontEffectColor=0,0,0,50
FontColor=#colorText#
FontFace=#fontName#
FontSize=10
AntiAlias=1
ClipString=1

[styleLeftText]
StringAlign=LEFT
; Meters using styleLeftText will be left-aligned.
StringCase=NONE
StringStyle=NORMAL
StringEffect=SHADOW
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

[styleRightText]
StringAlign=RIGHT
StringCase=NONE
StringStyle=NORMAL
StringEffect=SHADOW
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1

[styleBar]
BarColor=#colorBar#
BarOrientation=HORIZONTAL
SolidColor=255,255,255,15

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

[meterTitle]
Meter=STRING
MeterStyle=styleTitle
; Using MeterStyle=styleTitle will basically "copy" the
; contents of the [styleTitle] section here during runtime.
X=100
Y=7
W=190
H=18
Text="Zdrowie"

[meterLabelStatus]
Meter=STRING
MeterStyle=styleLeftText
X=5
Y=38
W=190
H=14
Text="Status"

[meterValueStatus]
Meter=STRING
MeterStyle=styleRightText
StringCase=UPPER
MeasureName=measureStatus
X=192
Y=0r
; To not overlap "Status"
W=145 
H=14
ClipString=2

[meterBarStatus]
Meter=BAR
MeterStyle=styleBar
MeasureName=measureZero
X=5
Y=52
W=190
H=1

[meterLabelLastSG]
Meter=STRING
MeterStyle=styleLeftText
X=5
Y=60
W=190
H=14
Text="Poziom cukru"

[meterValueLastSG]
Meter=STRING
MeterStyle=styleRightText
MeasureName=measureLastSG
X=192
Y=0r
W=190
H=14
Text="%1 mg/dL"

[meterBarLastSG]
Meter=BAR
MeterStyle=styleBar
MeasureName=measureZero
X=5
Y=74
W=190
H=1

[meterLabelMeasureTime]
Meter=STRING
MeterStyle=styleLeftText
X=5
Y=82
W=190
H=14
Text="Czas pomiaru"

[meterValueMeasureTime]
Meter=STRING
MeterStyle=styleRightText
MeasureName=measureTimeParsed
X=192
Y=0r
W=190
H=14
Text="%1"

[meterBarMeasureTime]
Meter=BAR
MeterStyle=styleBar
MeasureName=measureZero
X=5
Y=96
W=190
H=1

[meterLabelPumpBattery]
Meter=STRING
MeterStyle=styleLeftText
X=5
Y=104
W=190
H=14
Text="Bateria pompy"


[meterValuePumpBattery]
Meter=STRING
MeterStyle=styleRightText
MeasureName=measurePumpBattery
X=192
Y=0r
W=190
H=14
Text="%1%"

[meterBarPumpBattery]
Meter=BAR
MeterStyle=styleBar
MeasureName=measurePumpBattery
X=5
Y=118
W=190
H=1

[meterLabelSensorBattery]
Meter=STRING
MeterStyle=styleLeftText
X=5
Y=126
W=190
H=14
Text="Bateria sensora"

[meterValueSensorBattery]
Meter=STRING
MeterStyle=styleRightText
MeasureName=measureSensorBattery
X=192
Y=0r
W=190
H=14
Text="%1%"

[meterBarSensorBattery]
Meter=BAR
MeterStyle=styleBar
MeasureName=measureSensorBattery
X=5
Y=140
W=190
H=1